# @package _global_

model:
  name: vit_h                     # VIT-H variant
  img_size: 256
  ckpt: checkpoints/sam_vit_h.pth # VIT-H pretrained checkpoint
  lora_ckpt: null
  module: sam_lora_image_encoder
  rank: 4