name: sam_hybrid
module: model.sam_hybrid_adapter
sam_type: vit_b
adaptation_mode: encoder_frozen_decoder_ft
img_size: 224
rank: 4
sam_checkpoint: checkpoints/sam_vit_b_01ec64.pth
lora_checkpoint: null
