name: sam_hybrid
module: model.sam_hybrid_adapter
sam_type: vit_b
adaptation_mode: encoder_frozen_decoder_ft
img_size: 224
rank: 4
sam_checkpoint: checkpoints/sam_vit_b_01ec64.pth
# Set to checkpoint path for distillation, e.g.:
# lora_checkpoint: logs/encoder_frozen_decoder_ft/BUSBRA+BUSI+B/20260121_220309_bs4_lr0.0001/checkpoints/best_epoch_8_dice0.7650.pth
lora_checkpoint: /home/hheo/codes/papers/medfm/logs/encoder_frozen_decoder_ft/BUSBRA+BUSI+B/20260122_072746_bs4_lr0.0001/checkpoints/best_epoch_17_dice0.7324.pth
